# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-15 08:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200517_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 15, 8, 8, 38, 708943, tzinfo=utc)),
        ),
    ]
